console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log(4 * 4);
console.log(4 * 5);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log(4 * 4);
console.log(4 * 4);
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log(4 * 4);
console.log(4 * 4);
console.log("xdyixssxhisxdiisbb");
console.log("xdyixssxhisxdiisbb");
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 4);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
console.log(4 * 10);
